logger:
  default: warning
  logs:
    custom_components.wago: info

modbus:
  - name: modbus_hub
    type: tcp
    host: 192.168.2.49
    port: 502
    binary_sensors:
      - name: Kalt
        address: 12308
        device_class: cold

wago:
  - name: Wago
    covers:
      - name: Jal Dominik Süden
        address_set: 12356
        address_p: 13176
        address_a: 13184
        address_pos: 13192
        address_ang: 13200
        scan_interval: 5
        unique_id: jal_dominik_south
      - name: Jal Dominik Westen
        address_set: 12357
        address_p: 13208
        address_a: 13216
        address_pos: 13224
        address_ang: 13232
        scan_interval: 5
        unique_id: jal_dominik_west
    lights:
      - name: Dominik
        address_set: 12354
        address_rst: 12355
        address_val: 518
        address_brightness: 13168
        scan_interval: 5
        unique_id: light_dominik
      - name: Werkstatt
        address_set: 12336
        address_rst: 12336
        address_val: 570
        scan_interval: 5
        unique_id: light_werkstatt

