logger:
  default: warning
  logs:
    custom_components.wago: info

modbus:
  - name: modbus_hub
    type: tcp
    host: 192.168.2.49
    port: 502
    binary_sensors:
      - name: Kalt
        address: 12308
        device_class: cold

wago:
  - name: Wago
    covers:
      - name: Jal Dominik Süden
        address_set: 12591
        address_reg_pa: 12418
        address_reg_posang: 12419
        scan_interval: 5
        unique_id: jal_dominik_south
      - name: Jal Dominik Westen
        address_set: 12592
        address_reg_pa: 12420
        address_reg_posang: 12421
        scan_interval: 5
        unique_id: jal_dominik_west
    lights:
      - name: Dominik
        address_set: 12550
        address_rst: 12551
        address_ison: 12552
        address_valset: 13760
        address_brightness: 13768
        scan_interval: 5
        unique_id: light_dominik
      # - name: Werkstatt
      #   address_set: 
      #   address_rst: 
      #   address_ison: 
      #   scan_interval: 5
      #   unique_id: light_werkstatt

